arrows/urls.py
from django.conf.urls import include , url
from django.contrib import admin

urlpatterns = [
    url(r'^forwarder/',include('forwarder.urls')),
    url(r'^admin/', admin.site.urls),
]

forwarder/urls.py
from django.conf.urls import url

from .import views
from django.contrib.auth.views import login
app_name="forwarder"
urlpatterns = [
        url(r'^$' , views.index, name='index'),
        url(r'^login/$',login,{'template_name':'forwarder/login.html'}, name="login" ),
        url(r'^staff/$',views.staff),
        url(r'^apply/$',views.apply),
        url(r'^detail/$',views.detail, name="detail"),
]

forwarder/models.py
from django.db import models

# Create your models here.

forwarder/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return HttpResponse("hello there")

def staff(request):
    return render(request, 'forwarder/staff.html')

def apply(request):
    return render(request, 'forwarder/application_form.html')

def detail(request):
    return render(request, 'forwarder/detail.html')

forwarder/templates/forwarder/application_form.html
{% extends 'forwarder/base.html' %}
{% block head %}
<style media="screen">
  body{
    background: white;
  }

</style>
{% endblock %}
{% block body %}

      <div class="row container app_form">
        <form class="col s12 z-depth-4">
          <div class="row border">
            <div class="input-field col s6">
              <i class="material-icons prefix">account_circle</i>
              <input id="icon_prefix" type="text" class="validate">
              <label for="icon_prefix">First Name</label>
            </div>
            <div class="input-field col s6">
              <i class="material-icons prefix"></i>
              <input id="last_name" type="text" class="validate">
              <label for="last_name">Last Name</label>
            </div>

            <div class="input-field col s12">
              <i class="material-icons prefix">assignment_ind</i>
              <input id="admission_number" type="text" class="validate">
              <label for="admission_number">Admission Number</label>
            </div>
            <div class="input-field col s12">
              <i class="material-icons prefix">location_city</i>
              <input id="department" type="text" class="validate">
              <label for="department">Department</label>
            </div>
            <div class="input-field col s12">
              <i class="material-icons prefix">local_library</i>
              <input id="Semester" type="text" class="validate">
              <label for="Semester">Semester</label>
            </div>
            <div class="input-field col s12">
              <i class="material-icons prefix">face</i>
              <input id="date of birth" type="text" class="datepicker validate">
              <label for="date of birth">Date of birth</label>
            </div>
            <div class="input-field col s12">
              <i class="material-icons prefix">supervisor_account</i>
              <input id="guardian_name" type="text" class="validate">
              <label for="guardian_name">Guardian Name</label>
            </div>
            <div class="input-field col s12">
              <i class="material-icons prefix">style</i>
              <select>
                <option value="" disabled selected>Choose your option</option>
                <option>Welfare Board</option>
                <option>Character Certificate</option>
                <option>Bank Loan</option>
                <option>Embassy Attestation</option>
                <option>Issue of certificates</option>
                <option>Non-Receipt Applications</option>
                <option>Issue of Specific format certificates</option>
                <option>Others</option>
              </select>
              <label for="application_type">Application Type</label>
            </div>
          </div>
        </form>
      </div>



{% endblock %}

forwarder/templates/forwarder/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Arrows{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'forwarder/materialize.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'forwarder/style.css' %}">
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--fonts-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Satisfy"/>
    {% block head %}
    {% endblock %}
  </head>

  <body>


      <nav>
          <div class="nav-wrapper  black">
            <a href="#!" class="brand-logo">Arrow</a>
            <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
            <ul class="righthand right hide-on-med-and-down">
              <li><a href="sass.html">Home</a></li>
              <li><a href="badges.html">Contact</a></li>
              <li><a href="collapsible.html">Settings</a></li>
              <li><a href="mobile.html"></a>Logout</li>
            </ul>
            <ul class="side-nav" id="mobile-demo">
              <li><a href="sass.html">Home</a></li>
              <li><a href="badges.html">Contact</a></li>
              <li><a href="collapsible.html">Settings</a></li>
              <li><a href="mobile.html">Logout</a></li>
            </ul>
          </div>
      </nav>
















    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
    <!--Import jQuery before materialize.js-->
     <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
     <script type="text/javascript" src="{% static 'forwarder/materialize.min.js' %}"></script>
     <script type="text/javascript" src="{% static 'forwarder/main.js'%}">

     </script>
     {% block body %}
     {% endblock %}
  </body>

</html>

forwarder/templates/forwarder/detail.html
{% extends 'forwarder/base.html' %}
{% block head %}
<style media="screen">
  body{
    background:#5c6bc0  ;
  }

</style>
{% endblock %}
{% block body %}
<div class="container">
  <br>

  <div class="row z-depth-3 ">
    <div class="col s6  white">
      <div class="section">
        <h5>Name</h5>
        <p>Stuff</p>
      </div>
      <div class="divider"></div>
      <div class="section">
        <h5>Admission Number</h5>
        <p>Stuff</p>
      </div>
      <div class="divider"></div>
      <div class="section">
        <h5>Date of birth</h5>
        <p>Stuff</p>
      </div>
    </div>
    <div class="col s6 white">
      <div class="section">
        <h5>Department</h5>
        <p>Stuff</p>
      </div>
      <div class="divider"></div>
      <div class="section">
        <h5>Semester</h5>
        <p>Stuff</p>
      </div>
      <div class="divider"></div>
      <div class="section">
        <h5>Guardian name</h5>
        <p>Stuff</p>
      </div>
    </div>
    <div class="col s12 white">
      <div class="divider">

      </div>
      <div class="section">
        <h5>Application type and details</h5>
        <p>stuff</p>
      </div>

    </div>
  </div>
  <div class="align-center">
    <button type="submit" class=" waves-effect waves-light btn">FORWARD<i class="material-icons right">check</i></button>
    <button type="submit" class="waves-effect waves-light btn">REJECT<i class="material-icons right">close</i></button>

  </div>



</div>

  {% endblock %}

forwarder/templates/forwarder/login.html
{% extends 'forwarder/base.html' %}
{% block body %}
<div class="container login">
  <div class="form_bg z-depth-4 ">
    <h2>   LOGIN </h2>
    <div class="row">
      <form class="col s12" method="post">
        <div class="row">
          <div class="input-field col s12">

            <i class="material-icons prefix">account_circle</i>
            <input id="icon_prefix" type="text" class="validate">
            <label for="first_name">Username</label>
          </div>
          </div>
            <div class="row">
          <div class="input-field col s12 ">

            <i class="material-icons prefix">lock</i>
            <input id="password" type="password" class="validate">
            <label for="password">Password</label>
          </div>
        </div>
        <div class="align-center">
          <button type="submit" class="waves-effect waves-light btn">Submit<i class="material-icons right">send</i></button>


        </div>
      </form>


    <!--<form  method="post">
    {% csrf_token %}
    {{ form.as_p }}

      <button type="submit" class="btn btn-success">Login</button>

  </form>-->


  </div>

</div>


</div>
{% endblock %}

forwarder/templates/forwarder/staff.html
{% extends 'forwarder/base.html' %}
{% block head %}
<style media="screen">
  body{
    background: white;
  }

</style>
{% endblock %}
{% block body %}



  <div class="row  ">


    <div class="col s12 m3 l2 indigo lighten-2">

        <div class=" section ">
          <h5 >FILTER</h5>
          <div class="divider"></div>
        </div>

        <div class="row ">
          <div class="input-field col s12 white  ">
            <select >
              <option value="" disabled selected>Filter by</option>
              <option value="1">Year</option>
              <option value="2">Semester</option>
              <option value="3">Date</option>
            </select>

          </div>



      </div>




      </div>



        <div class="col s12 m9 l10 indigo lighten-3">

          <div class=" section ">
                <h5>REQUESTS</h5>
                <div class="divider"></div>

            </div>
            <ul class="collapsible " data-collapsible="accordion">
              <li>
                <div class="collapsible-header ">First</div>
                  <div class="collapsible-body"><span>Lorem ipsum dolor sit amet.</span>
                    <a class="waves-effect waves-light btn " href="{% url 'forwarder:detail' %}">Details</a>
                </div>
              </li>
              <li>
                <div class="collapsible-header ">Second</div>
                <div class="collapsible-body"><span>Lorem ipsum dolor sit amet.</span></div>
              </li>
              <li>
                <div class="collapsible-header ">Third</div>
                <div class="collapsible-body"><span>Lorem ipsum dolor sit amet.</span></div>
              </li>
              <li>
                <div class="collapsible-header ">Fourth</div>
                <div class="collapsible-body"><span>Lorem ipsum dolor sit amet.</span></div>
              </li>
              <li>
                <div class="collapsible-header ">Fifth</div>
                <div class="collapsible-body"><span>Lorem ipsum dolor sit amet.</span></div>
              </li>
              <li>
                <div class="collapsible-header ">Sixth</div>
                <div class="collapsible-body"><span>Lorem ipsum dolor sit amet.</span></div>
              </li>
            </ul>







        </div>







    </div>




{% endblock %}